# Change these first
owner: testRTC # Your GitHub username
repo: status-page # Your GitHub repository name

# Add your sites here
sites:
  -	name: Frontend
    url: https://app.testrtc.com/
  -	name: Backend
    url: https://app1.testrtc.com/api/status-page/system_name
  -	name: API (Staging)
    url: https://api.testrtc.com/v1st/statuspage
    headers:
      - "apikey: $API_KEY"
      - "Content-Type: application/json"    
  -	name: watchRTC (Staging)
    url: https://watchrtc-staging2.testrtc.com/healthcheck
  -	name: qualityRTC
    url: https://ping-test.testrtc.com/
  -	name: probeRTC
    url: https://probertc.testrtc.com/
  -	name: Home Page
    url: https://testrtc.com/
  - name: DNS Leak
    url: https://d178430f-11f6-45b9-be1e-6c9be44261ed.dnsleak.testrtc.com/dnsleak
  -	name: qualityRTC Speed Test us-east-2
    url: https://us-east-2.nettest.testrtc.com/country
  -	name: qualityRTC Speed Test eu-central-1
    url: https://eu-central-1.nettest.testrtc.com/country
  -	name: qualityRTC Speed Test eu-north-1
    url: https://eu-north-1.nettest.testrtc.com/country
  -	name: qualityRTC Speed Test eu-west-1
    url: https://eu-west-1.nettest.testrtc.com/country
  -	name: qualityRTC Speed Test eu-west-3
    url: https://eu-west-3.nettest.testrtc.com/country
  -	name: qualityRTC Speed Test us-east-1
    url: https://us-east-1.nettest.testrtc.com/country
  -	name: qualityRTC Speed Test us-west-2
    url: https://us-west-2.nettest.testrtc.com/country
  -	name: qualityRTC Speed Test sa-east-1
    url: https://sa-east-1.nettest.testrtc.com/country
  -	name: qualityRTC Speed Test ap-southeast-1
    url: https://ap-southeast-1.nettest.testrtc.com/country
  -	name: qualityRTC Speed Test ap-northeast-1
    url: https://ap-northeast-1.nettest.testrtc.com/country
  -	name: qualityRTC Speed Test ap-southeast-2
    url: https://ap-southeast-2.nettest.testrtc.com/country
  -	name: qualityRTC Speed Test af-south-1
    url: https://af-south-1.nettest.testrtc.com/country

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status-staging.testrtc.com
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/testRTC/status-page/master/static/img/testlogo.jpg
  name: Status
  introTitle: "testRTC - TEST & MONITOR YOUR WEBRTC-BASED APPLICATION AT SCALE"
  introMessage: testRTC service status page
  navbar:
    - title: Status
      href: /
    - title: testRTC
      href: https://testrtc.com/
    - title: Service
      href: https://app.testrtc.com/

i18n:
  footer: Copyright 2020 testRTC | All rights reserved

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
