# Change these first
owner: testRTC # Your GitHub username
repo: status-page # Your GitHub repository name

# Add your sites here
sites:
  - name: Google
    url: https://www.google.com
  - name: Wikipedia
    url: https://en.wikipedia.org
  - name: Hacker News
    url: https://news.ycombinator.com
  - name: Broken Site
    url: https://thissitedoesnotexist.com
  - name: Secret Site
    url: $SECRET_SITE

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.testrtc.com
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/testRTC/status-page/master/static/img/testlogo.jpg
  name:
  introTitle: "testRTC - TEST & MONITOR YOUR WEBRTC-BASED APPLICATION AT SCALE"
  introMessage: testRTC service status page
  navbar:
    - title: Status
      href: /
    - title: testRTC
      href: https://testrtc.com/
    - title: Service
      href: https://app.testrtc.com/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
